FROM mrsono0/base_project:nginx_flask
# FROM nginx
# MAINTAINER "Ivan Ermilov <mailto:ivan.s.ermilov@gmail.com>"

COPY ubuntu/default.conf /etc/nginx/conf.d/default.conf
COPY ubuntu/materialize.min.css /data/bde-css/materialize.min.css
COPY ubuntu/bde-hadoop.css /data/bde-css/bde-hadoop.css
