nginx:
  image: mrsono0/bigdata_project:hadoop_nginx
  hostname: nginx
  net: hadoop
  container_name: nginx
  ports:
    - "8080:80"

namenode:
  image: mrsono0/bigdata_project:hadoop_namenode
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/namenode:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=test
  env_file:
    - ./ubuntu/hadoop.env

resourcemanager:
  image: mrsono0/bigdata_project:hadoop_resourcemanager
  hostname: resourcemanager
  container_name: resourcemanager
  domainname: hadoop
  net: hadoop
  env_file:
    - ./ubuntu/hadoop.env

historyserver:
  image: mrsono0/bigdata_project:hadoop_historyserver
  hostname: historyserver
  container_name: historyserver
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/historyserver:/hadoop/yarn/timeline
  env_file:
    - ./ubuntu/hadoop.env

nodemanager1:
  image: mrsono0/bigdata_project:hadoop_nodemanager
  hostname: nodemanager1
  container_name: nodemanager1
  domainname: hadoop
  net: hadoop
  env_file:
    - ./ubuntu/hadoop.env

datanode1:
  image: mrsono0/bigdata_project:hadoop_datanode
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode1:/hadoop/dfs/data
  env_file:
    - ./ubuntu/hadoop.env

datanode2:
  image: mrsono0/bigdata_project:hadoop_datanode
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode2:/hadoop/dfs/data
  env_file:
    - ./ubuntu/hadoop.env

datanode3:
  image: mrsono0/bigdata_project:hadoop_datanode
  hostname: datanode3
  container_name: datanode3
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode3:/hadoop/dfs/data
  env_file:
    - ./ubuntu/hadoop.env
