FROM mrsono0/base_project:hadoop_base
# FROM bde2020/hadoop-base:1.1.0-hadoop2.7.1-java8
# MAINTAINER Ivan Ermilov <ivan.s.ermilov@gmail.com>

HEALTHCHECK CMD curl -f http://localhost:50075/ || exit 1

ENV HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
RUN mkdir -p /hadoop/dfs/data
VOLUME /hadoop/dfs/data

ADD ubuntu/run_hadoop_datanode.sh /run_hadoop_datanode.sh
RUN chmod a+x /run_hadoop_datanode.sh

EXPOSE 50075

CMD ["/run.sh"]
