FROM mrsono0/base_project:hadoop_base

# FROM bde2020/hadoop-base:1.1.0-hadoop2.7.1-java8
# MAINTAINER Ivan Ermilov <ivan.s.ermilov@gmail.com>

HEALTHCHECK CMD curl -f http://localhost:8042/ || exit 1

ADD ubuntu/run_hadoop_nodemanager.sh /run_hadoop_nodemanager.sh
RUN chmod a+x /run_hadoop_nodemanager.sh

EXPOSE 8042

CMD ["/run_hadoop_nodemanager.sh"]
