FROM mrsono0/base_project:hadoop_base
# FROM bde2020/hadoop-base:1.1.0-hadoop2.7.1-java8
# MAINTAINER Ivan Ermilov <ivan.s.ermilov@gmail.com>

HEALTHCHECK CMD curl -f http://localhost:50070/ || exit 1

ENV HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
RUN mkdir -p /hadoop/dfs/name
VOLUME /hadoop/dfs/name

ADD ubuntu/run_hadoop_namenode.sh /run_hadoop_namenode.sh
RUN chmod a+x /run_hadoop_namenode.sh

EXPOSE 50070

CMD ["/run_hadoop_namenode.sh"]
